### ISSUE TITLE
Application crashed and keeps crashing even after re-installation

### ISSUE THREAD

**Issue by rodgc** [twesterapp/twester#4] opened 2021-09-28 19:16 UTC
## Prerequisites

-   [X] I am on the [latest](https://github.com/twesterapp/twester/releases/latest) Twester version
-   [X] I have searched the [issues](https://github.com/twesterapp/twester/issues) of this repo and believe that this is not a duplicate

-   **OS version and name**: macOS Big Sur Version 11.5.2
-   **Twester version**: Version 1.0.0 (1.0.0)

## Issue

Application crash after some time of using it

![image](https://user-images.githubusercontent.com/16006361/135151167-cbf17cae-b3ba-4f33-b88e-7b8545b574ef.png)

Trying to reload App with the button or closing and reopening it, do not fix the issue

**Comment by ceoshikhar** [comment] 2021-09-28 20:18
@rodgc hey! 

Sorry about the app crashing. Can you please confirm that app is crashing even after you entirely close it and open it again?

**Comment by rodgc** [comment] 2021-09-28 20:20
@ceoshikhar  - Stil crashing, I have uninstalled it and re-installed it, and still have the issue

**Comment by ceoshikhar** [comment] 2021-09-28 20:21
@rodgc  Can you please tell me what was happening when this happened? I am really sorry that I haven't implemented a log report feature when the app crashes. So I can't look at what exactly went wrong. I think the next first thing I should be adding to Twester, should be a crash report feature.

**Comment by rodgc** [comment] 2021-09-28 20:22
@ceoshikhar - It was running fine for like 1 hr then it simply crash, I have it on the background running, so didn't see if there was an error o somehitng.

**Comment by ceoshikhar** [comment] 2021-09-28 20:23
@rodgc The app isn't working even after re-installation. My best guess would be that something went wrong with data and that wrong data got saved to the app's local storage. Can you delete the installation directory and re-install. Because normal uninstall and reinstall keeps the old local storage data.

**Comment by rodgc** [comment] 2021-09-28 20:24
@ceoshikhar - I  have already deleted all files related to the application when uninstalling it, still the same issue

**Comment by SuperQuentin** [comment] 2021-09-28 20:28
Same here

**Comment by ceoshikhar** [comment] 2021-09-28 20:28
@rodgc I can't think of any reason how the app could continue to crash even though it was working fine before. The only reason I could imagine was the local storage data being wrong. I am sorry but I can't think why is it crashing even after reinstalling. :( You are 100% sure that anything related to the app was removed?

**Comment by ceoshikhar** [comment] 2021-09-28 20:29
> Same here

On macOS ? Was running fine and then crashed and won't run even after re-install?

**Comment by rodgc** [comment] 2021-09-28 20:30
@ceoshikhar - Yeah, I also use [App Cleaner](https://freemacsoft.net/appcleaner/) to ensure everything is deleted

**Comment by SuperQuentin** [comment] 2021-09-28 20:31
No, I'm on windows 10 and I try to reinstall it I encounter an issue after trying to add a new streamer the app doesn't seem to take in consideration my action and just after it just doesn't want to work anymore

**Comment by ceoshikhar** [comment] 2021-09-28 20:31
@rodgc @SuperQuentin I don't have an access to mac. I generally light tested it on my VM. What I can do is run the app in development and production versions on macOS VM and then hopefully it will crash crash and I will know what's wrong.

**Comment by ceoshikhar** [comment] 2021-09-28 20:33
> No, I'm on windows 10 and I try to reinstall it I encounter an issue after trying to add a new streamer the app doesn't seem to take in consideration my action and just after it just doesn't want to work anymore

Please make sure you delete the installation directory. Even after `uninstall` or `remove program` on Windows 10, the local storage data will still be there. I am saying this because I have logged in to Twester and then uninstalled and reinstalled the app and my account's data like `streamers` list etc is still preserved.

**Comment by SuperQuentin** [comment] 2021-09-28 20:40
i remove all file at the folder C:\Users\username\AppData\Local\Programs\twester\ where it's install by default but there seem to be other folder and i can't find it. Have you an idea where data can be store ?

**Comment by SuperQuentin** [comment] 2021-09-28 20:41
> i remove all file at the folder C:\Users\username\AppData\Local\Programs\twester\ where it's install by default but there seem to be other folder and i can't find it. Have you an idea where data can be store ?

Wound it at C:\Users\username\AppData\Roaming\Twester

**Comment by ceoshikhar** [comment] 2021-09-28 20:43
> > i remove all file at the folder C:\Users\username\AppData\Local\Programs\twester\ where it's install by default but there seem to be other folder and i can't find it. Have you an idea where data can be store ?
> 
> Found it at C:\Users\username\AppData\Roaming\Twester

Please try to delete that and re-install the app and does it still crash or not?

Also, what error does it show for you on crash screen?

**Comment by SuperQuentin** [comment] 2021-09-28 20:44
> > > i remove all file at the folder C:\Users\username\AppData\Local\Programs\twester\ where it's install by default but there seem to be other folder and i can't find it. Have you an idea where data can be store ?
> > 
> > 
> > Found it at C:\Users\username\AppData\Roaming\Twester
> 
> Please try to delete that and re-install the app and does it still crash or not?
> 
> Also, what error does it show for you on crash screen?

Now it's working it ask my credentials but i kind of mistype my auth password and now i have captcha error

**Comment by ceoshikhar** [comment] 2021-09-28 20:48
I have mentioned about the `Captcha Required` error when the user fails the login attempt. Did you read it? Hopefully that will help. 

Also, do you remember the crash error message? It would be really helpful.

**Comment by ceoshikhar** [comment] 2021-09-28 20:49
@rodgc as you can see @SuperQuentin was facing the same app crashing error after re-install and it was fixed for @SuperQuentin by manually deleting the data files. I will try to figure out where they are installed for macOS. Removing them should solve the issue for you too.

**Comment by SuperQuentin** [comment] 2021-09-28 20:50
That was the same as on the screenshot

For the captcha error i reinstall the app and i was able to login again put the second factor auth doesn't seem to work, i enter the code one time and nothing happen and i try to do it another time but i have the error message below
![image](https://user-images.githubusercontent.com/36150436/135163579-d7d5111c-a566-4596-b176-31a7cd495359.png)

**Comment by rodgc** [comment] 2021-09-28 20:51
> That was the same as on the screenshot
> 
> For the captcha error i reinstall the app and i was able to login again put the second factor auth doesn't seem to work, i enter the code one time and nothing happen and i try to do it another time but i have the error message below ![image](https://user-images.githubusercontent.com/36150436/135163579-d7d5111c-a566-4596-b176-31a7cd495359.png)

Has the same issue now

**Comment by SuperQuentin** [comment] 2021-09-28 20:53
yay i will try to clone the project and debug it

**Comment by ceoshikhar** [comment] 2021-09-28 20:54
> > That was the same as on the screenshot
> > For the captcha error i reinstall the app and i was able to login again put the second factor auth doesn't seem to work, i enter the code one time and nothing happen and i try to do it another time but i have the error message below ![image](https://user-images.githubusercontent.com/36150436/135163579-d7d5111c-a566-4596-b176-31a7cd495359.png)
> 
> Has the same issue now

wait! your app crashing after re-installation issue is fixed?

**Comment by ceoshikhar** [comment] 2021-09-28 20:54
> yay i will try to clone the project and debug it

Thank you so much!

**Comment by SuperQuentin** [comment] 2021-09-28 21:02
![image](https://user-images.githubusercontent.com/36150436/135165131-a043d0a9-bc44-4070-ad07-9b1a6a40f8ac.png)
i can't do anything now i will check on another time

**Comment by SuperQuentin** [comment] 2021-09-28 21:12
![image](https://user-images.githubusercontent.com/36150436/135166474-d4e8cf63-27d4-44d9-9173-ee998e33447a.png)
same error on the auth page now

**Comment by ceoshikhar** [comment] 2021-09-28 21:24
> ![image](https://user-images.githubusercontent.com/36150436/135166474-d4e8cf63-27d4-44d9-9173-ee998e33447a.png) ![image](https://user-images.githubusercontent.com/36150436/135166830-d33cac55-06c6-4ed5-8f7d-4cf927d0c760.png)
> 
> same error on the auth page now

This is really helpful. It's pretty late for me right now. I will check it out tomorrow. I am pretty sure all I have to do is add a `?` to optionally chain whatever I am reading from `data`. Once again, thank you. 

PS - If you want, you can fix it and create a PR for this `data` undefined error on auth page. The problem is in `src/renderer/pages/AuthPage.tsx` and there should be 3 places where `data.something` is being checked on server response. Just have to add an optional flag to it.

### Example 

> from 

```ts
const something = data.something;
```
>to
 
```ts
const something = data?.something;
```

**Comment by ceoshikhar** [comment] 2021-09-28 22:28
@rodgc @SuperQuentin I have found the issue. Apparently one of the Twitch API end points have been changed and that change is a breaking change. I am looking into it.

The Twitch API that was being used to fetch channel info is returning `404` instead of the `data`.

![image](https://user-images.githubusercontent.com/62669971/135174309-ee828ce4-f414-4295-b431-ae079b77f6d9.png)

**Comment by ceoshikhar** [comment] 2021-09-28 22:51
The API being used is https://dev.twitch.tv/docs/api/reference#get-users and apparently its not working as expected.

**Comment by khl3o** [comment] 2021-09-29 13:21
same problem here with macOS

**Comment by ceoshikhar** [comment] 2021-09-29 13:24
Looks like the `client-id` being used right now to interact with Twitch API is not working. The App is crashing because the data in one of the main API calls is returning `404` instead of the expected data.

**Comment by ceoshikhar** [comment] 2021-09-29 17:53
@rodgc  @SuperQuentin @khl3o the PR to fix these crashing issues is in progress. The problem was that Twitch's Helix API had breaking changes. Twester was using those APIs to fetch profile picture URLs and channel info (showed on `Streamers` tab). The same API was used on the final step of login flow. 

So Twester was crashing for users who were logged in and login flow was failing.

### **Note: macOS users will have to manually download the new release version with the fix. Auto-Update should work for Windows and Linux users, you just have to close and reopen Twester for auto update to start. If it doesn't update from `v1.0.0` then manually update.**

**Comment by ceoshikhar** [comment] 2021-09-29 18:16
@rodgc @SuperQuentin @khl3o 

### Twester [v1.0.1](https://github.com/twesterapp/twester/releases/tag/v1.0.1) is released which fixed the issues causing Twester to crash ( for logged in user ) or user was not able to login ( login flow failed at final step ). 

Twester auto updated for me to **v1.0.1**. Although I would still get the app crashed screen but I have to wait for sometime while the download and installation happens in the background. Once that's completed, you will get a Windows Notification saying Twester v1.0.1 is installed, restart to use it. 

Please let me know if you are still facing this issue or is it resolved.

**Comment by khl3o** [comment] 2021-09-29 18:23
worked for me, thanks a lot

**Comment by rodgc** [comment] 2021-09-29 18:34
@ceoshikhar  - Thx working now

**Comment by ceoshikhar** [comment] 2021-09-29 18:45
Well looks likes it's fixed. I will be closing this issue now. Thank you everyone for helping make Twester better. ♥

**Closed by ceoshikhar** 2021-09-29 18:45 UTC
Labels: bug
