### ISSUE TITLE
Button/Option to run in tray

### ISSUE THREAD

**Issue by v6r** [twesterapp/twester#47] opened 2022-05-09 21:05 UTC
:)

**Comment by ceoshikhar** [comment] 2022-05-10 06:44
I will look into this over the coming weekend and keep you updated on this.

**Comment by v6r** [comment] 2022-05-18 06:11
> I will look into this over the coming weekend and keep you updated on this.

How is it going : )

**Comment by LeetHaxor** [comment] 2022-05-26 13:32
Any updates on this?

**Comment by ceoshikhar** [comment] 2022-05-26 19:29
Hey, sorry for no updates on this yet. Honestly I have been very busy. I hardly get the time or the energy to work on this at the moment but I do care about Twester. I will definitely look into this as soon as I can and update you on this.

PS - any help on this is welcome in regards to the technical side of the things like how to implement the "minimise to system tray" feature.

Once again, I'll get on this as soon as I can!

**Comment by ceoshikhar** [comment] 2022-05-28 17:16
Is this what you are looking for?

![](https://miro.medium.com/max/1400/1*i-YrogEPzEs2ov3wVVm-RQ.gif)

**Comment by v6r** [comment] 2022-05-28 22:12
yes exactly

**Comment by ceoshikhar** [comment] 2022-05-28 22:50
I have PR up with this feature implemented. Works for me as expected on macOS. If you guys have either Windows or Linux, please download from below and test it and let me know if it's working as expected for you or not. If any of the listed expected behaviour is not working then please bring it to my notice. 

Also, as I don't have access to Windows and Linux at the moment, I would greatly appreciate if you can share screen recording of the visual behaviour of this feature if it's working as expected.

[Linux](https://github.com/twesterapp/twester/releases/download/untagged-31f97342c5dd85d9b066/Twester-1.1.0.AppImage)
[macOS](https://github.com/twesterapp/twester/releases/download/untagged-31f97342c5dd85d9b066/Twester-1.1.0.dmg)
[Windows](https://github.com/twesterapp/twester/releases/download/untagged-31f97342c5dd85d9b066/Twester-Setup-1.1.0.exe)

### Expected behaviour -

1. When you click on cross(X) to close Twester, it should by default minimize to tray to keep running as usual.
2. Twester's icon should be visible in the tray.
3. Right click on Twester's icon in the tray and selecting "Show" should open the Twester back in the window.
4. Right click on Twester's icon in the tray and selecting "Exit" should quit/exit the Twester for good.

PS - I am thinking to add a `Settings` tab to the left sidebar above `Logout` button and add an option `Close to tray` to enable/disable this feature in the actual release. Thoughts on this?

**Comment by v6r** [comment] 2022-05-28 23:08
Thank you for implementing this. Twester is a really nice Project. I think an extra settings tab would be a very good idea. Maybe there are other suggestions that could be added to the settings. However, the links you provided cannot be downloaded for the updated twester version. It redicrects to a page that does not exist.

**Comment by LeetHaxor** [comment] 2022-05-29 05:29
Same issue as v6r, DL links are broken atm.

**Comment by ceoshikhar** [comment] 2022-05-29 05:36
@v6r @LeetHaxor I have updated the download link. It should work now.

**Comment by LeetHaxor** [comment] 2022-05-29 05:44
Just installed (Windows), and when I close to tray I can't get it to show again from right click (or double click) tray icon> show. Looking at task manager and it stays stuck under "background processes" and won't return to it's normal state.

**Comment by ceoshikhar** [comment] 2022-05-29 05:48
That's not what I was expecting at all. I will be setting up virtual machine for Windows and/or Linux and then test it myself.

**Comment by ceoshikhar** [comment] 2022-05-29 07:45
Well, I am having a hard time setting up virtual machine env for Windows/Linux on my M1 Mac. I don't think I will be able to continue on this for the next few weeks.

**Comment by LeetHaxor** [comment] 2022-05-29 07:50
No worries, it's great as is. Tray icon is more of a minor QoL improvement to an already perfectly functional program, imo. Thanks for the updates.

**Comment by ceoshikhar** [comment] 2022-05-29 07:56
I had been looking at the code and I think I found out the problem. I will be posting new build download links for you to test again. Should be a few minutes.

**Comment by ceoshikhar** [comment] 2022-05-29 08:05
New build download from [here](https://github.com/twesterapp/twester/releases/tag/v1.1.1). I am pretty sure, it should work now.

**Comment by LeetHaxor** [comment] 2022-05-29 08:11
Seems to work fine, I did get [this error](https://i.imgur.com/IYMBpQQ.png) initially, but can't reproduce it.

> New build download from [here](https://github.com/twesterapp/twester/releases/tag/v1.1.1). I am pretty sure, it should work now.

**Comment by ceoshikhar** [comment] 2022-05-29 08:15
@LeetHaxor  Weird, that error happened only at first and now it's fine? If that's the case then I guess that's not a deal breaker, right?

It would be nice if you figure out a way to reproduce it so that it can be fixed.

**Comment by ceoshikhar** [comment] 2022-05-29 08:16
@v6r waiting on you to test this feature on your machine and give feedback.

**Comment by LeetHaxor** [comment] 2022-05-29 08:23
@ceoshikhar I got it to happen again, but it's not consistent. It happened right when I clicked "show" from the tray. Also it was accompanied the second time by [this error](https://i.imgur.com/OkITl9O.png) also.

**Comment by ceoshikhar** [comment] 2022-05-29 08:34
@LeetHaxor I think I might have figured out the "Tray is destroyed" exception that is crashing Twester. Will soon comment the updated build download link.

**Comment by ceoshikhar** [comment] 2022-05-29 08:41
@LeetHaxor That error should be fixed [now](https://github.com/twesterapp/twester/releases/tag/v1.1.2)

**Comment by LeetHaxor** [comment] 2022-05-29 08:46
Seems to be working fine. I spammed show/hide, moved from visible/not visible on taskbar, spammed X/show, and no errors.

**Comment by ceoshikhar** [comment] 2022-05-29 08:48
Nice!

**Comment by ceoshikhar** [comment] 2022-05-29 08:51
I am not sure when this will be in an official release but there is already a pre-release for this feature and I recommend everyone who wants this feature until then to download the release from [here](https://github.com/twesterapp/twester/releases/tag/v1.1.2).

**Comment by v6r** [comment] 2022-05-29 10:46
> @v6r waiting on you to test this feature on your machine and give feedback.

Im on windows. Works completely fine.

**Closed** 2022-05-29 11:58 UTC
Labels: enhancement

**Comment by ceoshikhar** [comment] 2022-06-07 20:09
@v6r @LeetHaxor Release build(v1.1.0) with this feature is out! If you are on Windows or Linux, you would have already got the auto update but if you are on macOS you will have to manually download latest release. There is a "Settings" tab now with "Close to tray" and 2 other options.
